### ISSUE TITLE
Interchange trailer in separate class

### ISSUE THREAD

**Issue by rkotulan** [indice-co/EDI.Net#26] opened 2016-11-01 15:45 UTC
I have defined POCO Interchange and InterchangeTrailer in separate segment class

```csharp
    public class Interchange
    {
        public Interchange()
        {
            this.InterchangeHeader = new InterchangeHeader();
            this.Quote = new Quote();
            this.InterchangeTrailer = new InterchangeTrailer();
        }

        public InterchangeHeader InterchangeHeader { get; set; }

        public Quote Quote { get; set; }

        public InterchangeTrailer InterchangeTrailer { get; set; }
    }
```
```csharp
    [EdiSegment, EdiPath("UNZ")]
    public class InterchangeTrailer
    {
        [EdiValue("X(1)", Path = "UNZ/0")]
        public string TrailerControlCount { get; set; }

        [EdiValue("X(14)", Path = "UNZ/1")]
        public string TrailerControlReference { get; set; }
    }
```
If i try to deserialize edi file InterchangeTrailer is empty. 
Similar problem with UNH - message header.
Serialization is ok.

**Comment by cleftheris** [comment] 2016-11-01 15:59
@rkotulan this is by design and it is a known limitation of the deserializer. Check [my answer]( https://github.com/indice-co/EDI.Net/issues/14#issuecomment-244056179) to a similar question on issue 14. 

> the headers and footers of Interchanges, Messages and Groups define a "Logical" structure for an EDI transmission. So when trying to deserialize into dotnet classes in the current implementation they are considered to go into whatever class the attribute is appled upon. However, any other segment except those that are structural can be deserialized into separate [EdiSegment] decorated classes. Mabe in the future I could enhance this to be able to group properties of the header and footer separately but for the time being this is not allowed.

As a workaround you can copy all header and footer properties straight into the interchange class instead of the `InterchangeHeader` & `InterchangeTrailer` classes .

If this works for you give me an update so I can close this issue

**Comment by rkotulan** [comment] 2016-11-01 16:05
Thanks for clarification. Workaround works for me.

**Closed** 2016-11-01 16:13 UTC
Labels: question
