### ISSUE TITLE
Out Of Memory when using Conditional on NAD

### ISSUE THREAD

**Issue by Kirides** [indice-co/EDI.Net#70] opened 2017-10-27 11:03 UTC
While using the Conditional Attribute on my Segment, i end up in getting an Out Of Memory error.

Maybe i do not quite understand how to use the attributes correctly yet, or my schema just does not fit

( Edi Sample IFTMIN: https://pastebin.com/zYVnj4sV )
( Full classes :  https://pastebin.com/5wYTm5bZ (not 100% finished yet))

    public class Quote {
        [EdiCondition("FP", Path = "NAD[0][1]")]
        public NAD FreightPayer { get; set; }
    }

    [EdiSegmentGroup("NAD")]
    public class NAD
    {
        [EdiValue("X(3)", Path = "NAD/0/0")]
        public string PartyQualifier { get; set; }

        [EdiValue("X(35)", Path = "NAD/1/0")]
        public string PartyId { get; set; }

        [EdiValue("X(3)", Path = "NAD/1/2")]
        public string ResponsibleAgency { get; set; }

        [EdiValue("X(35)", Mandatory = true, Path = "NAD/2")]
        public string NameAndAddressDescription { get; set; }

        [EdiValue("X(35)", Mandatory = true, Path = "NAD/3")]
        public string PartyName { get; set; }

        [EdiValue("X(35)", Mandatory = true, Path = "NAD/4")]
        public string Street { get; set; }

        [EdiValue("X(35)", Path = "NAD/5")]
        public string CityName { get; set; }

        [EdiValue("X(17)", Path = "NAD/6")]
        public string CountrySubEntityDetails { get; set; }

        [EdiValue("X(3)", Path = "NAD/7")]
        public string CountryNameCode { get; set; }

        public CTA Kontakt { get; set; }

        [EdiCondition("TE", Path = "COM/0/1")]
        public COM Telefon { get; set; }

        [EdiCondition("EM", Path = "COM/0/1")]
        public COM Email { get; set; }
    }

Error
----
Testname:	ParseEdifact
Test FullName:	TA.EDI.Test.IFTMIN.ParseEdifact
Testquelle:	C:\SVN\TAEDIwc\trunk\TA.EDI.Test\IFTMIN.cs Zeile 18
Testergebnis:	Fehlgeschlagene
Testdauer:	0:00:08,5126838

Ergebnis StackTrace:	
bei System.Collections.Generic.Queue`1.SetCapacity(Int32 capacity)
   bei System.Collections.Generic.Queue`1.Enqueue(T item)
   bei indice.Edi.EdiSerializer.ConditionalMatch(EdiReader reader, EdiStructure currentStructure, EdiStructureType newContainerType, EdiPropertyDescriptor[] candidates) in C:\SVN\TAEDIwc\trunk\indice.Edi\EdiSerializer.cs:Zeile 506.
   bei indice.Edi.EdiSerializer.FindForCurrentSegment(EdiReader reader, EdiStructure currentStructure, EdiStructureType newContainerType) in C:\SVN\TAEDIwc\trunk\indice.Edi\EdiSerializer.cs:Zeile 435.
   bei indice.Edi.EdiSerializer.TryCreateContainer(EdiReader reader, Stack`1 stack, EdiStructureType newContainer) in C:\SVN\TAEDIwc\trunk\indice.Edi\EdiSerializer.cs:Zeile 371.
   bei indice.Edi.EdiSerializer.DeserializeInternal(EdiReader reader, Type objectType) in C:\SVN\TAEDIwc\trunk\indice.Edi\EdiSerializer.cs:Zeile 113.
   bei indice.Edi.EdiSerializer.Deserialize(EdiReader reader, Type objectType) in C:\SVN\TAEDIwc\trunk\indice.Edi\EdiSerializer.cs:Zeile 70.
   bei indice.Edi.EdiSerializer.Deserialize(TextReader reader, IEdiGrammar grammar, Type objectType) in C:\SVN\TAEDIwc\trunk\indice.Edi\EdiSerializer.cs:Zeile 48.
   bei indice.Edi.EdiSerializer.Deserialize[T](TextReader reader, IEdiGrammar grammar) in C:\SVN\TAEDIwc\trunk\indice.Edi\EdiSerializer.cs:Zeile 36.
   bei TA.EDI.Test.IFTMIN.ParseEdifact() in C:\SVN\TAEDIwc\trunk\TA.EDI.Test\IFTMIN.cs:Zeile 26.
Ergebnis Meldung:	
Die TA.EDI.Test.IFTMIN.ParseEdifact-Testmethode hat eine Ausnahme ausgelöst: 
System.OutOfMemoryException: Eine Ausnahme vom Typ "System.OutOfMemoryException" wurde ausgelöst.

**Comment by cleftheris** [comment] 2017-11-01 09:57
Hi @Kirides 

Ok I checked this and the issue is that you have annotated values with `X(512)` sizes like so
```csharp
[EdiValue("X(512)", Mandatory = true, Path = "FTX/3/0")]
public string FreeTextValue_1 { get; set; }
```
The maximum field size supported is that of a c# [byte](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/byte) (ranges from 0 - 255) so if you make it smaller you will be fine.

I have not found the time to check your transmission spec but if these kinds of sizes are possible then I should change my precision code to support [ushort](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ushort) 

So please check the spec and report back so I can close the issue

Cheers!
C.

**Comment by Kirides** [comment] 2017-11-01 10:51
Regarding the FTX : https://www.unece.org/trade/untdid/d01b/trsd/trsdftx.htm

Issued can be closed though, i checked the wrong Girls (0/1 instead of 0/0)

But now #71 stops any advancement

**Closed** 2017-11-01 11:24 UTC
Labels: bug
