### ISSUE TITLE
Is it by design or bug?

### ISSUE THREAD

**Issue by Drenalol** [indice-co/EDI.Net#176] opened 2020-10-26 18:11 UTC
Hi @cleftheris, can u please explain this example.

I have this DTOs

```c#
public class GithubIssue
    {
        public UNB InterchangeHeader { get; set; }
        public GithubMessage Message { get; set; }
        public UNZ InterchangeTrailer { get; set; }
    }

    [EdiMessage, EdiSegmentGroup("UNH", SequenceEnd = "UNZ")]
    public class GithubMessage
    {
        [EdiValue("X(14)", Mandatory = true, Description = "0062", Path = "UNH/0")]
        public string ReferenceNumberHeader { get; set; }

        public GithubGroup GithubGroup { get; set; }

        [EdiValue("X(14)", Mandatory = true, Description = "0062", Path = "UNT/1")]
        public string ReferenceNumberTrailer { get; set; }
    }

    [EdiSegment, EdiPath("ISS")]
    public class ISS
    {
        [EdiValue("9(3)", Path = "ISS/0")]
        public int Id { get; set; }

        [EdiValue("X(35)", Path = "ISS/1")]
        public string Title { get; set; }

        [EdiValue("X(15)", Path = "ISS/2")]
        public string Status { get; set; }

        [EdiValue("X(35)", Path = "ISS/3")]
        public string Author { get; set; }
    }

    [EdiSegment, EdiPath("USR")]
    public class USR
    {
        [EdiValue("9(3)", Path = "USR/0")]
        public int Id { get; set; }

        [EdiValue("X(35)", Path = "USR/1")]
        public string Title { get; set; }
    }

    [EdiSegmentGroup("ISS", SequenceEnd = "UNT")]
    public class GithubGroup
    {
        public ISS GithubIssue { get; set; }
        public USR GithubUser { get; set; }
    }
```

and this EDIFACT

```
UNB+GTHB:1+DRNL+CLHS+201026:2057+TEST0001+++O'
UNH+1337'
ISS+176+Is it by design or bug?+Open+Drenalol'
USR+1+Drenalol'
UNT+4+1337'
UNZ+1+TEST'
```

When i Deserialize EDIFACT to DTO ```typeof(GithubIssue)```, i'am always got ISS = null, but if i manually create DTO and Serialize to EDIFACT, its succesfully equals to ethalon.

Deserialize result:

```json
{
  "InterchangeHeader": {
    "SyntaxIdentifier": "GTHB",
    "SyntaxVersion": 1,
    "SenderIdentification": "DRNL",
    "RecipientIdentification": "CLHS",
    "Date": {
      "Value": "2020-10-26T00:00:00"
    },
    "Time": {
      "Value": "20:57:00"
    },
    "ControlReference": "TEST0001",
    "Priority": "O"
  },
  "Message": {
    "ReferenceNumberHeader": "1337",
    "GithubGroup": {
      "GithubIssue": null, <-- this
      "GithubUser": {
        "Id": 1,
        "Title": "Drenalol"
      }
    },
    "ReferenceNumberTrailer": "1337"
  },
  "InterchangeTrailer": {
    "ControlCount": 1,
    "ControlReference": "TEST"
  }
}
```

Workaround for this situation, unwrap ISS properties inside GithubGroup, and deserialize will be succesfully.

**Comment by rvandeweyer** [comment] 2020-11-02 15:59
Hi,

I am struggling with the same issue.  For every segment group, the **first** element is never deserialized. When i use a dummy , it works fine. So i end up having 20 dummies in my object tree ,....

`  [EdiSegmentGroup("SG30", SequenceEnd = "UNS", Start = "DUM")]
    public class LineItem
    {
        public DUM Dummy { get; set; }
        public CST ItemCode { get; set; } //48 custom status of goods

        public FTX ItemDescription { get; set; } 

       etc.....
}`

**Comment by rvandeweyer** [comment] 2020-11-02 17:18
Hi,
add-on the same is true when i use named segments in the segmentgroup , also here the first segment is not deserialized... 

``  [EdiSegment, EdiSegmentGroup("PAC", "PCI")]
    public class SG31
    {

        [EdiCondition("6", CheckFor = EdiConditionCheckType.Equal, Path = "PAC/0/0")]
        public PAC Package { get; set; }//60

        [EdiCondition("28", CheckFor = EdiConditionCheckType.Equal, Path = "PCI/0/0")]
        public PCI2 PackageIdentification { get; set; }//61


    }

Thanks

**Comment by cleftheris** [comment] 2020-11-02 17:59
@rvandeweyer This is by design. Check my detailed answer in this comment if you are interested in why this is the case https://github.com/indice-co/EDI.Net/issues/171#issuecomment-704745116

@Drenalol I haven't found the time to check this out thoroughly may be possible for the Message, Group and Interchange level (not so easy for other normal "segment groups"). Essentially both Message and Group are structural elements of all edi formats they are not composed in the same way as the restof the segments/segmentgroups (although I could drop these attributes in favor of the segement/segmentgroup). Also the segment/segmentgroup functionality has evolved greatly to support all-kinds of structures (nesting levels etc). On the other hand the standard structure has not yet seen the same love.

Main difference between plain old SegmentGroups  VS Message & FunctionalGroup:

consider this from wikipedia
```
 |_Service String Advice              UNA  Optional
 |____Interchange Header              UNB  Mandatory
 :    |___Functional Group Header     UNG  Conditional
 :    :   |___Message Header          UNH  Mandatory
 :    :   :   |__ User Data Segments          As required
 :    :   |__ Message Trailer         UNT  Mandatory
 :    |__ Functional Group Trailer    UNE  Conditional
 |___ Interchange Trailer             UNZ  Mandatory
```
If you see the following which is indented for the sake of clarity An **interchange** structure is defined by a header & treiler tags UNB & UNH the same goes for **message** and **functional group**. All of which have two segments and everything in between is contained inside the segment. On the contrary segment groups are defined by only one segment (lets say LIN) and all of the participating segments are inside the structure (no closing element). This is the reason they are handled differently at the moment.
```
UNB+UNOC:3+1234567891123:14+7080005059275:14:SPOTMARKED+101012:1104+HBQ001++++1'
       UNH+1+QUOTES:D:96A:UN:EDIEL2+S'
            LIN+1++1420:::SM'
	            DTM+324:201010192300201010192400:Z13'
	            PRI+CAL:-2100'
		            RNG+4+Z01:-0.1'
	            PRI+CAL:21000'
		            RNG+4+Z01:-0.1'
            LIN+2++1420:::SM'
	            DTM+324:201010200000201010200100:Z13'
	            PRI+CAL:-2100'
		            RNG+4+Z01:0'
	            PRI+CAL:21000'
		            RNG+4+Z01:0'
            LIN+3++1420:::SM'
	            DTM+324:201010200100201010200200:Z13'
	            PRI+CAL:-2100'
		            RNG+4+Z01:0'
	            PRI+CAL:21000'
            UNS+S'
            CNT+1:0'
            CNT+ZZZ:453600'
       UNT+158+1'
UNZ+1+20101000064507'
```

**Comment by rvandeweyer** [comment] 2020-11-02 19:05
Thanks a lot for the detailed answer and explanations. Looks clear, I will change my classes accordingly and use the inheritance of attributes.

**Closed** 2020-11-04 09:27 UTC
Labels: under-investigation
